version: '3'

services:
        web:
                container_name: web
                build:
                        context: ./
                        dockerfile: ./docker/web.docker
                volumes:
                        - ./:/var/www
                ports:
                        - "8080:80"
                networks:
                        - default
        app:
                container_name: app
                build:
                        context: ./
                        dockerfile: ./docker/app.docker
                volumes:
                        - ./:/var/www
                networks:
                        - default
                environment:
                        DB_HOST: db:3306
        db:
                container_name: database
                build:
                        context: ./
                        dockerfile: ./docker/database.docker
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: autozap
                ports:
                        - "33061:3306"
volumes:
        db_data:
